// Code generated by jtd-codegen, custom build, for Rust v0.2.1-custom

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub enum Root {
    #[serde(rename = "")]
    DefaultName,

    #[serde(rename = "$foo")]
    Foo,

    #[serde(rename = "0foo")]
    Foo0,

    #[serde(rename = "_foo")]
    Foo1,

    #[serde(rename = "foo\nbar")]
    FooBar,

    #[serde(rename = "foo bar")]
    FooBar0,

    #[serde(rename = "foo0bar")]
    Foo0bar,

    #[serde(rename = "foo﷽bar")]
    FooBar1,
}
