// Code generated by jtd-codegen, custom build, for Rust v0.2.1-custom

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Root {
    #[serde(rename = "bar")]
    pub bar: String,

    #[serde(rename = "baz")]
    pub baz: Vec<bool>,

    #[serde(rename = "foo")]
    pub foo: bool,

    #[serde(rename = "quux")]
    pub quux: Vec<bool>,
}
