// Code generated by jtd-codegen, custom build, for Rust v0.2.1-custom

use chrono::{DateTime, FixedOffset};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Root {
    #[serde(rename = "foo")]
    pub foo: Option<Box<DateTime<FixedOffset>>>,
}
