// Code generated by jtd-codegen, custom build, for Rust v0.2.1-custom

pub type Root = String;

pub type DefaultName = String;

pub type Foo = String;

pub type Foo0 = String;

pub type Foo1 = String;

pub type FooBar = String;

pub type FooBar0 = String;

pub type Foo0bar = String;

pub type FooBar1 = String;
